homework to RK1
java-park-mail-ru/3d-action-09-2016 pull request #1
Opened 2016-09-28 23:17 UTC by utrobin

2016-09-30 10:22 UTC, isopov reviewed
Ничего критичного пока, но если вы добавите тесты (раз они влезли перед первым РК), то будет круто!

2016-09-30 10:22 UTC, isopov commented on .gitignore
> +# Created by https://www.gitignore.io/api/java,intellij
Вам не кажется, что здесь много мусора? Монга, старый формат идеевских проектов, J2ME (прямо 20-м веком потянуло), ентерпрайзные сборки.
Я не настаиваю - но в своих проектах предпочитаю держать .gitignore чистым и понятным.

2016-09-30 10:22 UTC, isopov commented on README.md
> +Code examples for course "Java Programming" in https://park.mail.ru/
Не стесняйтесь полностью ридмишку править. Это уже не примеры кода))

2016-09-30 10:22 UTC, isopov commented on src/main/java/ru/javajava/services/AccountService.java
> +    private final Map<String, UserProfile> sessionIdToProfile = new ConcurrentHashMap<>();
Я бы положился на класс HttpSession.setAttribute("user", userName);

2016-09-30 10:22 UTC, isopov commented on swagger.yaml
> +swagger: '2.0'
Ссылку на вот это всё на вебе получится сделать? И такой вопрос - как вы считаете - вам сваггер взаимодействовать с фронтендом помогает или мешает? ))

2016-09-30 10:22 UTC, isopov commented on pom.xml
> +    <groupId>ru.javajava</groupId>
groupId совсем непонятный - принято использовать обратную запись домена, который находится под вашим контролем и относится к проекту (либо напрямую, либо как-то типа "родителя")

2016-09-30 10:22 UTC, isopov commented on pom.xml
> +    <groupId>ru.javajava</groupId>
Это может быть гитхаб например - com.gitub.java-park-mail-ru.3d-action-09-2016

2016-09-30 10:22 UTC, isopov commented on .idea/inspectionProfiles/tp_java_new.xml
> +<component name="InspectionProjectProfileManager">
профиль инспекций залит два раза - какой главный, каким вы пользуетесь? ))

2016-09-30 11:34 UTC, madsunrise commented on pom.xml
> +    <groupId>ru.javajava</groupId>
А у нас деплой на http://javajava.ru/

2016-09-30 11:46 UTC, madsunrise commented on swagger.yaml
> +swagger: '2.0'
надеемся, что после нормальной интеграции сваггера он станет нам незаменимым помощником))

2016-10-04 06:56 UTC, isopov commented on pom.xml
> +    <groupId>ru.javajava</groupId>
Тогда, прошу прощения - всё круто))

2016-10-10 17:08 UTC, isopov requested changes

2016-10-10 17:08 UTC, isopov commented on pom.xml
> +        <dependency>
Давайте удалим эту зависимость. Если хочется уже тесты (это хорошо, если хочется), то добавьте spring-boot-starter-test

2016-10-10 17:08 UTC, isopov commented on pom.xml
> +        <dependency>
И эту тоже удалите, и ничем не заменяйте - давайте использовать jackson

2016-10-10 17:08 UTC, isopov commented on .gitignore
> +!/.idea/*
Противоречащие друг другу строчки gitignore?

2016-10-10 17:08 UTC, isopov commented on javaNew.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Я этого не требовал оригинально на первое ревью, но раз оно уже прошло, и ко второму мы это решили требовать, то давайте сделаем уже сейчас - удалите и заигнорьте все проектный файлы Idea.

2016-10-10 17:08 UTC, isopov commented on src/test/java/ru/javajava/main/test.java
> +public class test {
Классы рекомендуется называть с большой буквы.

2016-10-10 17:08 UTC, isopov commented on src/main/resources/banner.txt
> +                                                -`
Может другой баннер, или удалить его совсем?

2016-10-11 18:56 UTC, isopov commented on pom.xml
> +            <groupId>junit</groupId>
эту зависимость я предлагал заменить на spring-boot-starter-test

2016-10-11 18:56 UTC, isopov commented on pom.xml
> +            <groupId>javax.servlet</groupId>
эту зависимость лучше убрать - мы будем пользоваться более новой сервлет-спецификацией в дальнейшем - пусть она приходит из спринга - там подходящая.

2016-10-11 18:58 UTC, madsunrise commented on pom.xml
> +            <groupId>junit</groupId>
а, неправильно понял..

2016-10-11 19:03 UTC, isopov commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
профиль инспекций лучше оставить в корне проекта для импорта в идею, а не единственным огрызком проектного файла идеи - ко второму РК это будет требованием.

2016-10-11 19:04 UTC, merged